//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_RIMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ERIMSEntities : DbContext
    {
        public ERIMSEntities()
            : base("name=ERIMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AcademicPaper> AcademicPaper { get; set; }
        public virtual DbSet<AcademicWorkYear> AcademicWorkYear { get; set; }
        public virtual DbSet<budgetYear> budgetYear { get; set; }
        public virtual DbSet<CategoryWork> CategoryWork { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<District> District { get; set; }
        public virtual DbSet<DocumentDownload> DocumentDownload { get; set; }
        public virtual DbSet<Education_Level> Education_Level { get; set; }
        public virtual DbSet<Expert> Expert { get; set; }
        public virtual DbSet<Innovator> Innovator { get; set; }
        public virtual DbSet<JoinDevelopmentTeam> JoinDevelopmentTeam { get; set; }
        public virtual DbSet<Journal> Journal { get; set; }
        public virtual DbSet<Level> Level { get; set; }
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<NameTitle> NameTitle { get; set; }
        public virtual DbSet<OverallOperation> OverallOperation { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<Province> Province { get; set; }
        public virtual DbSet<PublicRelation> PublicRelation { get; set; }
        public virtual DbSet<Researcher> Researcher { get; set; }
        public virtual DbSet<ResearchFuds> ResearchFuds { get; set; }
        public virtual DbSet<ResearchMonitoring> ResearchMonitoring { get; set; }
        public virtual DbSet<ResearchTopic> ResearchTopic { get; set; }
        public virtual DbSet<SubDistrict> SubDistrict { get; set; }
        public virtual DbSet<PercentActivities> PercentActivities { get; set; }
        public virtual DbSet<OperatingActivities> OperatingActivities { get; set; }
        public virtual DbSet<Innovation> Innovation { get; set; }
        public virtual DbSet<Research> Research { get; set; }
        public virtual DbSet<StatusActivity> StatusActivity { get; set; }
        public virtual DbSet<KnowledgeBox> KnowledgeBox { get; set; }
    }
}
