//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_RIMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    using E_RIMS.FileValidation;

    public partial class Journal
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string image { get; set; }
        [FileExtensionsValidationImage]
        public HttpPostedFileBase image2 { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string files { get; set; }
        [FileExtensionsValidationDoc]
        public HttpPostedFileBase files2 { get; set; }
        public Nullable<int> views { get; set; }
    }
}
