//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_RIMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;


    public partial class Member
    {
        public int id { get; set; }
        [Required(ErrorMessage = "กรุณากรอกชื่อผู้ใช้")]
        public string username { get; set; }
        [Required(ErrorMessage = "กรุณากรอกรหัสผ่าน")]
        [DataType(DataType.Password)]
        public string password { get; set; }
        [Required(ErrorMessage = "กรุณายืนยันรหัสผ่านอีกครั้ง")]
        [Compare(nameof(password),ErrorMessage = "รหัสผ่านไม่ตรงกัน")]
        public string confirmPassword { get; set; }
        public string role { get; set; }
        [Required(ErrorMessage = "กรุณากรอกอีเมล์")]
        [EmailAddress(ErrorMessage = "รูปแบบอีเมล์ผิดพลาด")]
        public string email { get; set; }
        public string researcherOwner { get; set; }
        public string innovatorOwner { get; set; }
    }
}
