//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_RIMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResearchMonitoring
    {
        public int id { get; set; }
        public string budgetYear { get; set; }
        public string department { get; set; }
        public string workName { get; set; }
        public string overallOperation { get; set; }
        public string operation { get; set; }
        public string category { get; set; }
        public Nullable<int> progress { get; set; }
        public string creator { get; set; }
        public string docUpload { get; set; }
        public string updates { get; set; }
    }
}
