using E_RIMS.FileValidation;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_RIMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Research
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string name { get; set; }
        public string @abstract { get; set; }
        public string category { get; set; }
        public string creator { get; set; }
        public string files { get; set; }
        [FileExtensionsValidationDoc]
        public HttpPostedFileBase files2 { get; set; }
    }
}
